# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get atomrootfsinit could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/atomrootfsinit/0.6.12"
SRC_URI += "git://github.com/NeroReflex/atomrootfsinit.git;protocol=https;nobranch=1;branch=main"
SRC_URI[libc-0.2.173.sha256sum] = "d8cfeafaffdbc32176b64fb251369d52ea9f0a8fbc6f8759edffef7b525d64bb"
SRCREV = "bf064e92929627710ed8d15382e74b3f86013e72"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""


# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/libc/0.2.173 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://GPL-2.0-or-later;md5=generateme \
"

SUMMARY = "Simple rust software to mount filesystems"
HOMEPAGE = "https://github.com/NeroReflex/atomrootfsinit"
LICENSE = "GPL-2.0-or-later"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include atomrootfsinit-${PV}.inc
include atomrootfsinit.inc