SUMMARY = "RustDesk - Remote Desktop Software"
DESCRIPTION = "RustDesk is a remote desktop software that is open-source and easy to use."
HOMEPAGE = "https://rustdesk.com/"

LICENSE = "AGPL-3.0-or-later"

LIC_FILES_CHKSUM = "file://LICENCE;md5=4ae09d45eac4aa08d013b5f2e01c67f6"

SRC_URI = " \
    git://github.com/rustdesk/rustdesk.git;protocol=https;nobranch=1;branch=main;rev=317639169359936f7f9f85ef445ec9774218772d \
    git://github.com/microsoft/vcpkg.git;protocol=https;nobranch=1;branch=main;rev=e6e4bc74aaf5c63dfc358810594f662f7e9bc4d4 \
"

S = "${WORKDIR}"

inherit cargo

SRC_URI += " \
    crate://crates.io/ab_glyph/0.2.31 \
    crate://crates.io/ab_glyph_rasterizer/0.1.10 \
    crate://crates.io/addr2line/0.22.0 \
    crate://crates.io/adler/1.0.2 \
    crate://crates.io/aes/0.8.4 \
    crate://crates.io/ahash/0.7.8 \
    crate://crates.io/ahash/0.8.12 \
    crate://crates.io/aho-corasick/1.1.3 \
    crate://crates.io/alloc-no-stdlib/2.0.4 \
    crate://crates.io/alloc-stdlib/0.2.2 \
    crate://crates.io/alsa/0.9.0 \
    crate://crates.io/alsa-sys/0.3.1 \
    crate://crates.io/android-activity/0.6.0 \
    crate://crates.io/android-properties/0.2.2 \
    crate://crates.io/android-tzdata/0.1.1 \
    crate://crates.io/android-wakelock/0.1.0 \
    crate://crates.io/android_log-sys/0.3.1 \
    crate://crates.io/android_logger/0.13.3 \
    crate://crates.io/android_system_properties/0.1.5 \
    crate://crates.io/ansi_term/0.12.1 \
    crate://crates.io/anstream/0.6.14 \
    crate://crates.io/anstyle/1.0.7 \
    crate://crates.io/anstyle-parse/0.2.4 \
    crate://crates.io/anstyle-query/1.1.0 \
    crate://crates.io/anstyle-wincon/3.0.3 \
    crate://crates.io/anyhow/1.0.98 \
    crate://crates.io/arboard/3.4.0 \
    crate://crates.io/arrayref/0.3.9 \
    crate://crates.io/arrayvec/0.7.6 \
    crate://crates.io/as-raw-xcb-connection/1.0.1 \
    crate://crates.io/associative-cache/1.0.1 \
    crate://crates.io/async-broadcast/0.5.1 \
    crate://crates.io/async-channel/2.3.1 \
    crate://crates.io/async-compression/0.4.11 \
    crate://crates.io/async-executor/1.12.0 \
    crate://crates.io/async-fs/1.6.0 \
    crate://crates.io/async-io/1.13.0 \
    crate://crates.io/async-io/2.3.3 \
    crate://crates.io/async-lock/2.8.0 \
    crate://crates.io/async-lock/3.4.0 \
    crate://crates.io/async-process/1.8.1 \
    crate://crates.io/async-recursion/1.1.1 \
    crate://crates.io/async-signal/0.2.8 \
    crate://crates.io/async-task/4.7.1 \
    crate://crates.io/async-trait/0.1.80 \
    crate://crates.io/atk/0.18.0 \
    crate://crates.io/atk-sys/0.18.0 \
    crate://crates.io/atomic-waker/1.1.2 \
    crate://crates.io/atty/0.2.14 \
    crate://crates.io/auto_impl/1.3.0 \
    crate://crates.io/autocfg/1.3.0 \
    crate://crates.io/autocfg/0.1.8 \
    crate://crates.io/backtrace/0.3.73 \
    crate://crates.io/base32/0.4.0 \
    crate://crates.io/base64/0.22.1 \
    crate://crates.io/base64/0.21.7 \
    crate://crates.io/base64ct/1.6.0 \
    crate://crates.io/bindgen/0.59.2 \
    crate://crates.io/bindgen/0.69.4 \
    crate://crates.io/bindgen/0.71.1 \
    crate://crates.io/bindgen/0.65.1 \
    crate://crates.io/bit_field/0.10.2 \
    crate://crates.io/bitflags/1.3.2 \
    crate://crates.io/bitflags/2.9.1 \
    crate://crates.io/bitvec/1.0.1 \
    crate://crates.io/block/0.1.6 \
    crate://crates.io/block-buffer/0.10.4 \
    crate://crates.io/block2/0.5.1 \
    crate://crates.io/blocking/1.6.1 \
    crate://crates.io/brotli/3.5.0 \
    crate://crates.io/brotli-decompressor/2.5.1 \
    crate://crates.io/bumpalo/3.16.0 \
    crate://crates.io/bytecodec/0.4.15 \
    crate://crates.io/bytemuck/1.23.2 \
    crate://crates.io/bytemuck_derive/1.10.1 \
    crate://crates.io/byteorder/1.5.0 \
    crate://crates.io/bytes/1.10.1 \
    crate://crates.io/bzip2/0.4.4 \
    crate://crates.io/bzip2-sys/0.1.11+1.0.8 \
    crate://crates.io/cairo-rs/0.18.5 \
    crate://crates.io/cairo-sys-rs/0.18.2 \
    crate://crates.io/calloop/0.13.0 \
    crate://crates.io/calloop-wayland-source/0.3.0 \
    crate://crates.io/cc/1.2.13 \
    crate://crates.io/cesu8/1.1.0 \
    crate://crates.io/cexpr/0.6.0 \
    crate://crates.io/cfg-expr/0.15.8 \
    crate://crates.io/cfg-if/0.1.10 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/cfg_aliases/0.2.1 \
    crate://crates.io/cfg_aliases/0.1.1 \
    crate://crates.io/chrono/0.4.41 \
    crate://crates.io/cidr-utils/0.5.11 \
    crate://crates.io/cipher/0.4.4 \
    crate://crates.io/clang-sys/1.8.1 \
    crate://crates.io/clap/4.5.8 \
    crate://crates.io/clap/2.34.0 \
    crate://crates.io/clap_builder/4.5.8 \
    crate://crates.io/clap_lex/0.7.1 \
    crate://crates.io/clipboard/0.1.0 \
    crate://crates.io/clipboard-master/4.0.0-beta.6 \
    crate://crates.io/clipboard-win/5.4.0 \
    crate://crates.io/cloudabi/0.0.3 \
    crate://crates.io/cocoa/0.25.0 \
    crate://crates.io/cocoa/0.24.1 \
    crate://crates.io/cocoa/0.20.2 \
    crate://crates.io/cocoa-foundation/0.1.2 \
    crate://crates.io/color_quant/1.1.0 \
    crate://crates.io/colorchoice/1.0.1 \
    crate://crates.io/combine/4.6.7 \
    crate://crates.io/concurrent-queue/2.5.0 \
    crate://crates.io/confy/0.4.0-2 \
    crate://crates.io/const_fn/0.4.10 \
    crate://crates.io/const_format/0.2.32 \
    crate://crates.io/const_format_proc_macros/0.2.32 \
    crate://crates.io/constant_time_eq/0.2.6 \
    crate://crates.io/constant_time_eq/0.1.5 \
    crate://crates.io/core-foundation/0.9.4 \
    crate://crates.io/core-foundation/0.7.0 \
    crate://crates.io/core-foundation/0.10.1 \
    crate://crates.io/core-foundation-sys/0.7.0 \
    crate://crates.io/core-foundation-sys/0.8.7 \
    crate://crates.io/core-graphics/0.22.3 \
    crate://crates.io/core-graphics/0.19.2 \
    crate://crates.io/core-graphics/0.23.2 \
    crate://crates.io/core-graphics-types/0.1.3 \
    crate://crates.io/core-media-sys/0.1.2 \
    crate://crates.io/core-text/19.2.0 \
    crate://crates.io/core-video-sys/0.1.4 \
    crate://crates.io/core_maths/0.1.1 \
    crate://crates.io/coreaudio-rs/0.11.3 \
    crate://crates.io/coreaudio-sys/0.2.15 \
    crate://crates.io/cpal/0.15.3 \
    crate://crates.io/cpufeatures/0.2.12 \
    crate://crates.io/crc/3.3.0 \
    crate://crates.io/crc-catalog/2.4.0 \
    crate://crates.io/crc32fast/1.4.2 \
    crate://crates.io/crossbeam-channel/0.5.13 \
    crate://crates.io/crossbeam-deque/0.8.5 \
    crate://crates.io/crossbeam-epoch/0.9.18 \
    crate://crates.io/crossbeam-queue/0.3.11 \
    crate://crates.io/crossbeam-utils/0.8.20 \
    crate://crates.io/crunchy/0.2.2 \
    crate://crates.io/crypto-common/0.1.6 \
    crate://crates.io/ctor-lite/0.1.0 \
    crate://crates.io/ctrlc/3.4.4 \
    crate://crates.io/cursor-icon/1.2.0 \
    crate://crates.io/dashmap/6.1.0 \
    crate://crates.io/dasp/0.11.0 \
    crate://crates.io/dasp_envelope/0.11.0 \
    crate://crates.io/dasp_frame/0.11.0 \
    crate://crates.io/dasp_interpolate/0.11.0 \
    crate://crates.io/dasp_peak/0.11.0 \
    crate://crates.io/dasp_ring_buffer/0.11.0 \
    crate://crates.io/dasp_rms/0.11.0 \
    crate://crates.io/dasp_sample/0.11.0 \
    crate://crates.io/dasp_signal/0.11.0 \
    crate://crates.io/dasp_slice/0.11.0 \
    crate://crates.io/dasp_window/0.11.1 \
    crate://crates.io/data-encoding/2.9.0 \
    crate://crates.io/dbus/0.9.7 \
    crate://crates.io/dbus-crossroads/0.5.2 \
    crate://crates.io/debug-helper/0.3.13 \
    crate://crates.io/default-net/0.14.1 \
    crate://crates.io/default_net/0.1.0 \
    crate://crates.io/deranged/0.3.11 \
    crate://crates.io/derivative/2.2.0 \
    crate://crates.io/digest/0.10.7 \
    crate://crates.io/directories-next/2.0.0 \
    crate://crates.io/dirs/4.0.0 \
    crate://crates.io/dirs/2.0.2 \
    crate://crates.io/dirs/5.0.1 \
    crate://crates.io/dirs-next/2.0.0 \
    crate://crates.io/dirs-sys/0.3.7 \
    crate://crates.io/dirs-sys/0.4.1 \
    crate://crates.io/dirs-sys-next/0.1.2 \
    crate://crates.io/dispatch/0.2.0 \
    crate://crates.io/dlib/0.5.2 \
    crate://crates.io/dlopen/0.1.8 \
    crate://crates.io/dlopen2/0.4.1 \
    crate://crates.io/dlopen2_derive/0.2.0 \
    crate://crates.io/dlopen_derive/0.1.4 \
    crate://crates.io/dlv-list/0.3.0 \
    crate://crates.io/docopt/1.1.1 \
    crate://crates.io/downcast-rs/1.2.1 \
    crate://crates.io/dpi/0.1.1 \
    crate://crates.io/drm/0.12.0 \
    crate://crates.io/drm-ffi/0.8.0 \
    crate://crates.io/drm-fourcc/2.2.0 \
    crate://crates.io/drm-sys/0.7.0 \
    crate://crates.io/dtoa/0.4.8 \
    crate://crates.io/dunce/1.0.5 \
    crate://crates.io/dylib_virtual_display/0.1.0 \
    crate://crates.io/ed25519/1.5.3 \
    crate://crates.io/either/1.13.0 \
    crate://crates.io/enigo/0.0.14 \
    crate://crates.io/enquote/1.1.0 \
    crate://crates.io/enum-map/2.7.3 \
    crate://crates.io/enum-map-derive/0.17.0 \
    crate://crates.io/enumflags2/0.7.10 \
    crate://crates.io/enumflags2_derive/0.7.10 \
    crate://crates.io/env_filter/0.1.3 \
    crate://crates.io/env_logger/0.11.6 \
    crate://crates.io/env_logger/0.9.3 \
    crate://crates.io/env_logger/0.10.2 \
    crate://crates.io/epoll/4.3.3 \
    crate://crates.io/equivalent/1.0.1 \
    crate://crates.io/errno/0.3.9 \
    crate://crates.io/error-code/3.2.0 \
    crate://crates.io/evdev/0.11.5 \
    crate://crates.io/event-listener/5.3.1 \
    crate://crates.io/event-listener/2.5.3 \
    crate://crates.io/event-listener/3.1.0 \
    crate://crates.io/event-listener-strategy/0.5.2 \
    crate://crates.io/exr/1.72.0 \
    crate://crates.io/fastrand/2.1.0 \
    crate://crates.io/fastrand/1.9.0 \
    crate://crates.io/fdeflate/0.3.4 \
    crate://crates.io/field-offset/0.3.6 \
    crate://crates.io/filedescriptor/0.8.2 \
    crate://crates.io/filetime/0.2.23 \
    crate://crates.io/fixedbitset/0.4.2 \
    crate://crates.io/flate2/1.0.30 \
    crate://crates.io/flexi_logger/0.27.4 \
    crate://crates.io/flume/0.11.0 \
    crate://crates.io/fnv/1.0.7 \
    crate://crates.io/fon/0.6.0 \
    crate://crates.io/fontconfig-parser/0.5.8 \
    crate://crates.io/fontdb/0.23.0 \
    crate://crates.io/foreign-types/0.3.2 \
    crate://crates.io/foreign-types/0.5.0 \
    crate://crates.io/foreign-types-macros/0.2.3 \
    crate://crates.io/foreign-types-shared/0.3.1 \
    crate://crates.io/foreign-types-shared/0.1.1 \
    crate://crates.io/form_urlencoded/1.2.1 \
    crate://crates.io/fruitbasket/0.10.0 \
    crate://crates.io/fsevent/2.1.2 \
    crate://crates.io/fsevent-sys/4.1.0 \
    crate://crates.io/fuchsia-cprng/0.1.1 \
    crate://crates.io/funty/2.0.0 \
    crate://crates.io/futures/0.3.30 \
    crate://crates.io/futures-channel/0.3.31 \
    crate://crates.io/futures-core/0.3.31 \
    crate://crates.io/futures-executor/0.3.30 \
    crate://crates.io/futures-io/0.3.31 \
    crate://crates.io/futures-lite/2.3.0 \
    crate://crates.io/futures-lite/1.13.0 \
    crate://crates.io/futures-macro/0.3.31 \
    crate://crates.io/futures-sink/0.3.31 \
    crate://crates.io/futures-task/0.3.31 \
    crate://crates.io/futures-util/0.3.31 \
    crate://crates.io/gdk/0.18.0 \
    crate://crates.io/gdk-pixbuf/0.18.5 \
    crate://crates.io/gdk-pixbuf-sys/0.18.0 \
    crate://crates.io/gdk-sys/0.18.0 \
    crate://crates.io/gdkwayland-sys/0.18.0 \
    crate://crates.io/gdkx11-sys/0.18.0 \
    crate://crates.io/generic-array/0.14.7 \
    crate://crates.io/gethostname/0.4.3 \
    crate://crates.io/getrandom/0.3.2 \
    crate://crates.io/getrandom/0.2.15 \
    crate://crates.io/gif/0.13.1 \
    crate://crates.io/gimli/0.29.0 \
    crate://crates.io/gio/0.18.4 \
    crate://crates.io/gio-sys/0.18.1 \
    crate://crates.io/git2/0.16.1 \
    crate://crates.io/glib/0.10.3 \
    crate://crates.io/glib/0.18.5 \
    crate://crates.io/glib-macros/0.10.1 \
    crate://crates.io/glib-macros/0.18.5 \
    crate://crates.io/glib-sys/0.10.1 \
    crate://crates.io/glib-sys/0.18.1 \
    crate://crates.io/glob/0.3.1 \
    crate://crates.io/gobject-sys/0.18.0 \
    crate://crates.io/gobject-sys/0.10.0 \
    crate://crates.io/gstreamer/0.16.7 \
    crate://crates.io/gstreamer-app/0.16.5 \
    crate://crates.io/gstreamer-app-sys/0.9.1 \
    crate://crates.io/gstreamer-base/0.16.5 \
    crate://crates.io/gstreamer-base-sys/0.9.1 \
    crate://crates.io/gstreamer-sys/0.9.1 \
    crate://crates.io/gstreamer-video/0.16.7 \
    crate://crates.io/gstreamer-video-sys/0.9.1 \
    crate://crates.io/gtk/0.18.1 \
    crate://crates.io/gtk-sys/0.18.0 \
    crate://crates.io/gtk3-macros/0.18.0 \
    crate://crates.io/half/2.4.1 \
    crate://crates.io/hashbrown/0.14.5 \
    crate://crates.io/hashbrown/0.15.4 \
    crate://crates.io/hashbrown/0.12.3 \
    crate://crates.io/hbb_common/0.1.0 \
    crate://crates.io/heck/0.4.1 \
    crate://crates.io/heck/0.3.3 \
    crate://crates.io/heck/0.5.0 \
    crate://crates.io/hermit-abi/0.4.0 \
    crate://crates.io/hermit-abi/0.3.9 \
    crate://crates.io/hermit-abi/0.5.0 \
    crate://crates.io/hermit-abi/0.1.19 \
    crate://crates.io/hex/0.4.3 \
    crate://crates.io/hmac/0.12.1 \
    crate://crates.io/home/0.5.9 \
    crate://crates.io/hound/3.5.1 \
    crate://crates.io/html-escape/0.2.13 \
    crate://crates.io/http/1.3.1 \
    crate://crates.io/http-body/1.0.1 \
    crate://crates.io/http-body-util/0.1.3 \
    crate://crates.io/httparse/1.10.1 \
    crate://crates.io/humantime/2.1.0 \
    crate://crates.io/hyper/1.6.0 \
    crate://crates.io/hyper-rustls/0.27.6 \
    crate://crates.io/hyper-tls/0.6.0 \
    crate://crates.io/hyper-util/0.1.12 \
    crate://crates.io/iana-time-zone/0.1.60 \
    crate://crates.io/iana-time-zone-haiku/0.1.2 \
    crate://crates.io/idna/0.5.0 \
    crate://crates.io/image/0.24.9 \
    crate://crates.io/image/0.25.1 \
    crate://crates.io/impersonate_system/0.1.0 \
    crate://crates.io/include_dir/0.7.4 \
    crate://crates.io/include_dir_macros/0.7.4 \
    crate://crates.io/indexmap/2.2.6 \
    crate://crates.io/inotify/0.10.2 \
    crate://crates.io/inotify-sys/0.1.5 \
    crate://crates.io/inout/0.1.3 \
    crate://crates.io/instant/0.1.13 \
    crate://crates.io/io-lifetimes/1.0.11 \
    crate://crates.io/ioctl-rs/0.1.6 \
    crate://crates.io/ipnet/2.9.0 \
    crate://crates.io/is-terminal/0.4.16 \
    crate://crates.io/is_debug/1.0.1 \
    crate://crates.io/is_terminal_polyfill/1.70.0 \
    crate://crates.io/itertools/0.9.0 \
    crate://crates.io/itertools/0.12.1 \
    crate://crates.io/itoa/1.0.11 \
    crate://crates.io/itoa/0.3.4 \
    crate://crates.io/jni/0.21.1 \
    crate://crates.io/jni-sys/0.3.0 \
    crate://crates.io/jobserver/0.1.31 \
    crate://crates.io/jpeg-decoder/0.3.1 \
    crate://crates.io/js-sys/0.3.77 \
    crate://crates.io/kcp-sys/0.1.0 \
    crate://crates.io/keepawake/0.4.3 \
    crate://crates.io/kernel32-sys/0.2.2 \
    crate://crates.io/keyboard-types/0.7.0 \
    crate://crates.io/kurbo/0.9.5 \
    crate://crates.io/lazy_static/1.5.0 \
    crate://crates.io/lazycell/1.3.0 \
    crate://crates.io/lebe/0.5.2 \
    crate://crates.io/libappindicator/0.9.0 \
    crate://crates.io/libappindicator-sys/0.9.0 \
    crate://crates.io/libc/0.2.171 \
    crate://crates.io/libdbus-sys/0.2.5 \
    crate://crates.io/libgit2-sys/0.14.2+1.5.1 \
    crate://crates.io/libloading/0.8.4 \
    crate://crates.io/libloading/0.7.4 \
    crate://crates.io/libm/0.2.8 \
    crate://crates.io/libpulse-binding/2.28.1 \
    crate://crates.io/libpulse-simple-binding/2.28.1 \
    crate://crates.io/libpulse-simple-sys/1.21.1 \
    crate://crates.io/libpulse-sys/1.21.0 \
    crate://crates.io/libredox/0.1.3 \
    crate://crates.io/libsodium-sys/0.2.7 \
    crate://crates.io/libxdo/0.6.0 \
    crate://crates.io/libxdo-sys/0.11.0 \
    crate://crates.io/libz-sys/1.1.18 \
    crate://crates.io/line-wrap/0.2.0 \
    crate://crates.io/linux-raw-sys/0.3.8 \
    crate://crates.io/linux-raw-sys/0.4.14 \
    crate://crates.io/linux-raw-sys/0.6.5 \
    crate://crates.io/lock_api/0.4.12 \
    crate://crates.io/log/0.4.22 \
    crate://crates.io/lru-slab/0.1.2 \
    crate://crates.io/mac_address/1.1.7 \
    crate://crates.io/mach2/0.4.2 \
    crate://crates.io/machine-uid/0.3.0 \
    crate://crates.io/magnum-opus/0.4.0 \
    crate://crates.io/malloc_buf/0.0.6 \
    crate://crates.io/matches/0.1.10 \
    crate://crates.io/md5/0.7.0 \
    crate://crates.io/memalloc/0.1.0 \
    crate://crates.io/memchr/2.7.4 \
    crate://crates.io/memmap2/0.9.8 \
    crate://crates.io/memoffset/0.9.1 \
    crate://crates.io/memoffset/0.7.1 \
    crate://crates.io/memoffset/0.6.5 \
    crate://crates.io/metal/0.18.0 \
    crate://crates.io/mime/0.3.17 \
    crate://crates.io/minimal-lexical/0.2.1 \
    crate://crates.io/miniz_oxide/0.7.4 \
    crate://crates.io/mio/1.0.3 \
    crate://crates.io/mio/0.8.11 \
    crate://crates.io/mozjpeg/0.10.11 \
    crate://crates.io/mozjpeg-sys/2.2.2 \
    crate://crates.io/muda/0.13.5 \
    crate://crates.io/muldiv/0.2.1 \
    crate://crates.io/nanorand/0.7.0 \
    crate://crates.io/nasm-rs/0.3.0 \
    crate://crates.io/native-tls/0.2.12 \
    crate://crates.io/native-windows-gui/1.0.13 \
    crate://crates.io/ndk/0.9.0 \
    crate://crates.io/ndk/0.7.0 \
    crate://crates.io/ndk/0.8.0 \
    crate://crates.io/ndk-context/0.1.1 \
    crate://crates.io/ndk-sys/0.5.0+25.2.9519653 \
    crate://crates.io/ndk-sys/0.6.0+11769913 \
    crate://crates.io/ndk-sys/0.4.1+23.1.7779620 \
    crate://crates.io/netlink-packet-core/0.5.0 \
    crate://crates.io/netlink-packet-route/0.15.0 \
    crate://crates.io/netlink-packet-utils/0.5.2 \
    crate://crates.io/netlink-sys/0.8.6 \
    crate://crates.io/nix/0.26.4 \
    crate://crates.io/nix/0.23.2 \
    crate://crates.io/nix/0.29.0 \
    crate://crates.io/nix/0.28.0 \
    crate://crates.io/nix/0.25.1 \
    crate://crates.io/nokhwa/0.10.7 \
    crate://crates.io/nokhwa-bindings-linux/0.1.1 \
    crate://crates.io/nokhwa-bindings-macos/0.2.2 \
    crate://crates.io/nokhwa-bindings-windows/0.4.2 \
    crate://crates.io/nokhwa-core/0.1.5 \
    crate://crates.io/nom/7.1.3 \
    crate://crates.io/ntapi/0.4.1 \
    crate://crates.io/nu-ansi-term/0.46.0 \
    crate://crates.io/nu-ansi-term/0.49.0 \
    crate://crates.io/num-bigint/0.4.6 \
    crate://crates.io/num-conv/0.1.0 \
    crate://crates.io/num-derive/0.4.2 \
    crate://crates.io/num-derive/0.3.3 \
    crate://crates.io/num-integer/0.1.46 \
    crate://crates.io/num-rational/0.3.2 \
    crate://crates.io/num-traits/0.1.43 \
    crate://crates.io/num-traits/0.2.19 \
    crate://crates.io/num_cpus/1.16.0 \
    crate://crates.io/num_enum/0.5.11 \
    crate://crates.io/num_enum/0.7.2 \
    crate://crates.io/num_enum_derive/0.5.11 \
    crate://crates.io/num_enum_derive/0.7.2 \
    crate://crates.io/num_threads/0.1.7 \
    crate://crates.io/objc/0.2.7 \
    crate://crates.io/objc-foundation/0.1.1 \
    crate://crates.io/objc-sys/0.3.5 \
    crate://crates.io/objc2/0.5.2 \
    crate://crates.io/objc2-app-kit/0.2.2 \
    crate://crates.io/objc2-cloud-kit/0.2.2 \
    crate://crates.io/objc2-contacts/0.2.2 \
    crate://crates.io/objc2-core-data/0.2.2 \
    crate://crates.io/objc2-core-image/0.2.2 \
    crate://crates.io/objc2-core-location/0.2.2 \
    crate://crates.io/objc2-encode/4.0.3 \
    crate://crates.io/objc2-foundation/0.2.2 \
    crate://crates.io/objc2-link-presentation/0.2.2 \
    crate://crates.io/objc2-metal/0.2.2 \
    crate://crates.io/objc2-quartz-core/0.2.2 \
    crate://crates.io/objc2-symbols/0.2.2 \
    crate://crates.io/objc2-ui-kit/0.2.2 \
    crate://crates.io/objc2-uniform-type-identifiers/0.2.2 \
    crate://crates.io/objc2-user-notifications/0.2.2 \
    crate://crates.io/objc_exception/0.1.2 \
    crate://crates.io/objc_id/0.1.1 \
    crate://crates.io/object/0.36.1 \
    crate://crates.io/oboe/0.6.1 \
    crate://crates.io/oboe-sys/0.6.1 \
    crate://crates.io/once_cell/1.19.0 \
    crate://crates.io/openssl/0.10.68 \
    crate://crates.io/openssl-macros/0.1.1 \
    crate://crates.io/openssl-probe/0.1.5 \
    crate://crates.io/openssl-sys/0.9.104 \
    crate://crates.io/option-ext/0.2.0 \
    crate://crates.io/orbclient/0.3.48 \
    crate://crates.io/ordered-multimap/0.4.3 \
    crate://crates.io/ordered-stream/0.2.0 \
    crate://crates.io/os-version/0.2.0 \
    crate://crates.io/os_pipe/1.2.0 \
    crate://crates.io/osascript/0.3.0 \
    crate://crates.io/overload/0.1.1 \
    crate://crates.io/owned_ttf_parser/0.25.1 \
    crate://crates.io/pam/0.7.0 \
    crate://crates.io/pam-macros/0.0.3 \
    crate://crates.io/pam-sys/1.0.0-alpha4 \
    crate://crates.io/pango/0.18.3 \
    crate://crates.io/pango-sys/0.18.0 \
    crate://crates.io/parity-tokio-ipc/0.7.3-5 \
    crate://crates.io/parking/2.2.0 \
    crate://crates.io/parking_lot/0.12.3 \
    crate://crates.io/parking_lot_core/0.9.10 \
    crate://crates.io/password-hash/0.4.2 \
    crate://crates.io/paste/1.0.15 \
    crate://crates.io/pbkdf2/0.11.0 \
    crate://crates.io/peeking_take_while/0.1.2 \
    crate://crates.io/percent-encoding/2.3.1 \
    crate://crates.io/petgraph/0.6.5 \
    crate://crates.io/phf/0.7.24 \
    crate://crates.io/phf/0.11.3 \
    crate://crates.io/phf_codegen/0.7.24 \
    crate://crates.io/phf_codegen/0.11.3 \
    crate://crates.io/phf_generator/0.7.24 \
    crate://crates.io/phf_generator/0.11.3 \
    crate://crates.io/phf_shared/0.11.3 \
    crate://crates.io/phf_shared/0.7.24 \
    crate://crates.io/piet/0.6.2 \
    crate://crates.io/piet-coregraphics/0.6.2 \
    crate://crates.io/pin-project/1.1.5 \
    crate://crates.io/pin-project-internal/1.1.5 \
    crate://crates.io/pin-project-lite/0.2.14 \
    crate://crates.io/pin-utils/0.1.0 \
    crate://crates.io/piper/0.2.3 \
    crate://crates.io/pkg-config/0.3.30 \
    crate://crates.io/plist/1.6.1 \
    crate://crates.io/png/0.17.13 \
    crate://crates.io/polling/2.8.0 \
    crate://crates.io/polling/3.7.2 \
    crate://crates.io/portable-pty/0.8.1 \
    crate://crates.io/powerfmt/0.2.0 \
    crate://crates.io/ppv-lite86/0.2.17 \
    crate://crates.io/pretty-hex/0.2.1 \
    crate://crates.io/prettyplease/0.2.20 \
    crate://crates.io/proc-macro-crate/0.1.5 \
    crate://crates.io/proc-macro-crate/2.0.2 \
    crate://crates.io/proc-macro-crate/1.3.1 \
    crate://crates.io/proc-macro-error/1.0.4 \
    crate://crates.io/proc-macro-error-attr/1.0.4 \
    crate://crates.io/proc-macro2/1.0.93 \
    crate://crates.io/proc-macro2/0.4.30 \
    crate://crates.io/protobuf/3.7.2 \
    crate://crates.io/protobuf-codegen/3.7.2 \
    crate://crates.io/protobuf-parse/3.7.2 \
    crate://crates.io/protobuf-support/3.7.2 \
    crate://crates.io/qoi/0.4.1 \
    crate://crates.io/qrcode-generator/4.1.9 \
    crate://crates.io/qrcodegen/1.8.0 \
    crate://crates.io/quest/0.3.0 \
    crate://crates.io/quick-xml/0.30.0 \
    crate://crates.io/quick-xml/0.31.0 \
    crate://crates.io/quick-xml/0.34.0 \
    crate://crates.io/quinn/0.11.8 \
    crate://crates.io/quinn-proto/0.11.12 \
    crate://crates.io/quinn-udp/0.5.12 \
    crate://crates.io/quote/0.6.13 \
    crate://crates.io/quote/1.0.36 \
    crate://crates.io/r-efi/5.2.0 \
    crate://crates.io/radium/0.7.0 \
    crate://crates.io/rand/0.9.0 \
    crate://crates.io/rand/0.6.5 \
    crate://crates.io/rand/0.8.5 \
    crate://crates.io/rand_chacha/0.3.1 \
    crate://crates.io/rand_chacha/0.9.0 \
    crate://crates.io/rand_chacha/0.1.1 \
    crate://crates.io/rand_core/0.9.3 \
    crate://crates.io/rand_core/0.3.1 \
    crate://crates.io/rand_core/0.6.4 \
    crate://crates.io/rand_core/0.4.2 \
    crate://crates.io/rand_hc/0.1.0 \
    crate://crates.io/rand_isaac/0.1.1 \
    crate://crates.io/rand_jitter/0.1.4 \
    crate://crates.io/rand_os/0.1.3 \
    crate://crates.io/rand_pcg/0.1.2 \
    crate://crates.io/rand_xorshift/0.1.1 \
    crate://crates.io/raw-window-handle/0.6.2 \
    crate://crates.io/raw-window-handle/0.5.2 \
    crate://crates.io/rayon/1.10.0 \
    crate://crates.io/rayon-core/1.12.1 \
    crate://crates.io/rdev/0.5.0-2 \
    crate://crates.io/rdrand/0.4.0 \
    crate://crates.io/redox_syscall/0.4.1 \
    crate://crates.io/redox_syscall/0.5.2 \
    crate://crates.io/redox_users/0.4.5 \
    crate://crates.io/regex/1.11.1 \
    crate://crates.io/regex-automata/0.4.9 \
    crate://crates.io/regex-syntax/0.8.5 \
    crate://crates.io/remote_printer/0.1.0 \
    crate://crates.io/repng/0.2.2 \
    crate://crates.io/reqwest/0.12.15 \
    crate://crates.io/rgb/0.8.50 \
    crate://crates.io/ring/0.17.14 \
    crate://crates.io/ringbuf/0.3.3 \
    crate://crates.io/roxmltree/0.20.0 \
    crate://crates.io/rpassword/7.3.1 \
    crate://crates.io/rpassword/2.1.0 \
    crate://crates.io/rtoolbox/0.0.2 \
    crate://crates.io/runas/1.2.0 \
    crate://crates.io/rust-ini/0.18.0 \
    crate://crates.io/rust-pulsectl/0.2.12 \
    crate://crates.io/rustc-demangle/0.1.24 \
    crate://crates.io/rustc-hash/1.1.0 \
    crate://crates.io/rustc-hash/2.1.1 \
    crate://crates.io/rustc_version/0.4.0 \
    crate://crates.io/rustdesk/1.4.2 \
    crate://crates.io/rustdesk-portable-packer/1.4.2 \
    crate://crates.io/rustix/0.38.34 \
    crate://crates.io/rustix/0.37.27 \
    crate://crates.io/rustls/0.23.26 \
    crate://crates.io/rustls-native-certs/0.8.1 \
    crate://crates.io/rustls-pemfile/2.2.0 \
    crate://crates.io/rustls-pki-types/1.11.0 \
    crate://crates.io/rustls-platform-verifier/0.5.1 \
    crate://crates.io/rustls-platform-verifier-android/0.1.0 \
    crate://crates.io/rustls-webpki/0.103.1 \
    crate://crates.io/rustversion/1.0.17 \
    crate://crates.io/ryu/1.0.18 \
    crate://crates.io/same-file/1.0.6 \
    crate://crates.io/schannel/0.1.23 \
    crate://crates.io/sciter-rs/0.5.57 \
    crate://crates.io/scoped-tls/1.0.1 \
    crate://crates.io/scopeguard/1.2.0 \
    crate://crates.io/scrap/0.5.0 \
    crate://crates.io/sctk-adwaita/0.10.1 \
    crate://crates.io/security-framework/3.2.0 \
    crate://crates.io/security-framework/2.10.0 \
    crate://crates.io/security-framework-sys/2.14.0 \
    crate://crates.io/semver/1.0.23 \
    crate://crates.io/serde/0.9.15 \
    crate://crates.io/serde/1.0.203 \
    crate://crates.io/serde_derive/1.0.203 \
    crate://crates.io/serde_json/1.0.118 \
    crate://crates.io/serde_json/0.9.10 \
    crate://crates.io/serde_repr/0.1.19 \
    crate://crates.io/serde_spanned/0.6.6 \
    crate://crates.io/serde_urlencoded/0.7.1 \
    crate://crates.io/serial/0.4.0 \
    crate://crates.io/serial-core/0.4.0 \
    crate://crates.io/serial-unix/0.4.0 \
    crate://crates.io/serial-windows/0.4.0 \
    crate://crates.io/sha1/0.10.6 \
    crate://crates.io/sha2/0.10.8 \
    crate://crates.io/shadow-rs/0.21.0 \
    crate://crates.io/sharded-slab/0.1.7 \
    crate://crates.io/shared_library/0.1.9 \
    crate://crates.io/shared_memory/0.12.4 \
    crate://crates.io/shell-words/1.1.0 \
    crate://crates.io/shlex/1.3.0 \
    crate://crates.io/shutdown_hooks/0.1.0 \
    crate://crates.io/signal-hook-registry/1.4.2 \
    crate://crates.io/signature/1.6.4 \
    crate://crates.io/simd-adler32/0.3.7 \
    crate://crates.io/siphasher/1.0.1 \
    crate://crates.io/siphasher/0.2.3 \
    crate://crates.io/slab/0.4.9 \
    crate://crates.io/slotmap/1.0.7 \
    crate://crates.io/smallvec/1.15.1 \
    crate://crates.io/smithay-client-toolkit/0.19.2 \
    crate://crates.io/smol_str/0.2.2 \
    crate://crates.io/socket2/0.4.10 \
    crate://crates.io/socket2/0.3.19 \
    crate://crates.io/socket2/0.5.10 \
    crate://crates.io/sodiumoxide/0.2.7 \
    crate://crates.io/softbuffer/0.4.5 \
    crate://crates.io/spin/0.9.8 \
    crate://crates.io/static_assertions/1.1.0 \
    crate://crates.io/strict-num/0.1.1 \
    crate://crates.io/strsim/0.11.1 \
    crate://crates.io/strsim/0.8.0 \
    crate://crates.io/strsim/0.10.0 \
    crate://crates.io/strum/0.18.0 \
    crate://crates.io/strum/0.24.1 \
    crate://crates.io/strum_macros/0.24.3 \
    crate://crates.io/strum_macros/0.18.0 \
    crate://crates.io/stun_codec/0.3.5 \
    crate://crates.io/stunclient/0.4.1 \
    crate://crates.io/subtle/2.6.1 \
    crate://crates.io/syn/2.0.98 \
    crate://crates.io/syn/0.15.44 \
    crate://crates.io/syn/1.0.109 \
    crate://crates.io/sync_wrapper/1.0.2 \
    crate://crates.io/sys-locale/0.3.1 \
    crate://crates.io/sysinfo/0.29.10 \
    crate://crates.io/system-configuration/0.5.1 \
    crate://crates.io/system-configuration-sys/0.5.0 \
    crate://crates.io/system-deps/6.2.2 \
    crate://crates.io/system-deps/1.3.2 \
    crate://crates.io/system_shutdown/4.0.1 \
    crate://crates.io/tao/0.25.0 \
    crate://crates.io/tao-macros/0.1.2 \
    crate://crates.io/tap/1.0.1 \
    crate://crates.io/target-lexicon/0.12.14 \
    crate://crates.io/target_build_utils/0.3.1 \
    crate://crates.io/tauri-winrt-notification/0.1.3 \
    crate://crates.io/tempfile/3.10.1 \
    crate://crates.io/termcolor/1.4.1 \
    crate://crates.io/terminfo/0.8.0 \
    crate://crates.io/termios/0.3.3 \
    crate://crates.io/termios/0.2.2 \
    crate://crates.io/textwrap/0.11.0 \
    crate://crates.io/tfc/0.7.0 \
    crate://crates.io/thiserror/1.0.61 \
    crate://crates.io/thiserror/2.0.11 \
    crate://crates.io/thiserror-impl/2.0.11 \
    crate://crates.io/thiserror-impl/1.0.61 \
    crate://crates.io/thread_local/1.1.8 \
    crate://crates.io/tiff/0.9.1 \
    crate://crates.io/time/0.3.36 \
    crate://crates.io/time/0.1.45 \
    crate://crates.io/time-core/0.1.2 \
    crate://crates.io/time-macros/0.2.18 \
    crate://crates.io/tiny-skia/0.11.4 \
    crate://crates.io/tiny-skia-path/0.11.4 \
    crate://crates.io/tiny-xlib/0.2.4 \
    crate://crates.io/tinyvec/1.6.1 \
    crate://crates.io/tinyvec_macros/0.1.1 \
    crate://crates.io/tokio/1.44.2 \
    crate://crates.io/tokio-macros/2.5.0 \
    crate://crates.io/tokio-native-tls/0.3.1 \
    crate://crates.io/tokio-rustls/0.26.0 \
    crate://crates.io/tokio-socks/0.5.2-3 \
    crate://crates.io/tokio-socks/0.5.2 \
    crate://crates.io/tokio-tungstenite/0.26.2 \
    crate://crates.io/tokio-util/0.7.15 \
    crate://crates.io/toml/0.8.2 \
    crate://crates.io/toml/0.7.8 \
    crate://crates.io/toml/0.5.11 \
    crate://crates.io/toml_datetime/0.6.3 \
    crate://crates.io/toml_edit/0.19.15 \
    crate://crates.io/toml_edit/0.20.2 \
    crate://crates.io/totp-rs/5.5.1 \
    crate://crates.io/tower/0.5.2 \
    crate://crates.io/tower-layer/0.3.3 \
    crate://crates.io/tower-service/0.3.3 \
    crate://crates.io/tracing/0.1.41 \
    crate://crates.io/tracing-attributes/0.1.29 \
    crate://crates.io/tracing-core/0.1.34 \
    crate://crates.io/tracing-log/0.2.0 \
    crate://crates.io/tracing-subscriber/0.3.19 \
    crate://crates.io/trackable/1.3.0 \
    crate://crates.io/trackable/0.2.24 \
    crate://crates.io/trackable_derive/1.0.0 \
    crate://crates.io/tray-icon/0.14.3 \
    crate://crates.io/tree_magic_mini/3.1.5 \
    crate://crates.io/try-lock/0.2.5 \
    crate://crates.io/ttf-parser/0.25.1 \
    crate://crates.io/tungstenite/0.26.2 \
    crate://crates.io/typenum/1.17.0 \
    crate://crates.io/tz-rs/0.6.14 \
    crate://crates.io/tzdb/0.5.10 \
    crate://crates.io/tzdb/0.6.1 \
    crate://crates.io/tzdb_data/0.1.2 \
    crate://crates.io/uds_windows/1.1.0 \
    crate://crates.io/uname/0.1.1 \
    crate://crates.io/unic-bidi/0.9.0 \
    crate://crates.io/unic-char-property/0.9.0 \
    crate://crates.io/unic-char-range/0.9.0 \
    crate://crates.io/unic-common/0.9.0 \
    crate://crates.io/unic-ucd-bidi/0.9.0 \
    crate://crates.io/unic-ucd-version/0.9.0 \
    crate://crates.io/unicode-bidi/0.3.15 \
    crate://crates.io/unicode-ident/1.0.12 \
    crate://crates.io/unicode-normalization/0.1.23 \
    crate://crates.io/unicode-segmentation/1.11.0 \
    crate://crates.io/unicode-width/0.1.13 \
    crate://crates.io/unicode-xid/0.1.0 \
    crate://crates.io/unicode-xid/0.2.4 \
    crate://crates.io/untrusted/0.9.0 \
    crate://crates.io/url/2.5.2 \
    crate://crates.io/urlencoding/2.1.3 \
    crate://crates.io/users/0.10.0 \
    crate://crates.io/users/0.11.0 \
    crate://crates.io/utf-8/0.7.6 \
    crate://crates.io/utf8-width/0.1.7 \
    crate://crates.io/utf8parse/0.2.2 \
    crate://crates.io/uuid/1.16.0 \
    crate://crates.io/v4l/0.14.0 \
    crate://crates.io/v4l2-sys-mit/0.3.0 \
    crate://crates.io/valuable/0.1.1 \
    crate://crates.io/vcpkg/0.2.15 \
    crate://crates.io/vec_map/0.8.2 \
    crate://crates.io/version-compare/0.2.0 \
    crate://crates.io/version-compare/0.0.10 \
    crate://crates.io/version_check/0.9.4 \
    crate://crates.io/virtual_display/0.1.0 \
    crate://crates.io/waker-fn/1.2.0 \
    crate://crates.io/walkdir/2.5.0 \
    crate://crates.io/wallpaper/3.2.0 \
    crate://crates.io/want/0.3.1 \
    crate://crates.io/wasi/0.10.0+wasi-snapshot-preview1 \
    crate://crates.io/wasi/0.11.0+wasi-snapshot-preview1 \
    crate://crates.io/wasi/0.14.2+wasi-0.2.4 \
    crate://crates.io/wasite/0.1.0 \
    crate://crates.io/wasm-bindgen/0.2.100 \
    crate://crates.io/wasm-bindgen-backend/0.2.100 \
    crate://crates.io/wasm-bindgen-futures/0.4.50 \
    crate://crates.io/wasm-bindgen-macro/0.2.100 \
    crate://crates.io/wasm-bindgen-macro-support/0.2.100 \
    crate://crates.io/wasm-bindgen-shared/0.2.100 \
    crate://crates.io/wayland-backend/0.3.6 \
    crate://crates.io/wayland-client/0.31.5 \
    crate://crates.io/wayland-csd-frame/0.3.0 \
    crate://crates.io/wayland-cursor/0.31.5 \
    crate://crates.io/wayland-protocols/0.32.3 \
    crate://crates.io/wayland-protocols-plasma/0.3.3 \
    crate://crates.io/wayland-protocols-wlr/0.3.3 \
    crate://crates.io/wayland-scanner/0.31.4 \
    crate://crates.io/wayland-sys/0.31.4 \
    crate://crates.io/web-sys/0.3.77 \
    crate://crates.io/web-time/1.1.0 \
    crate://crates.io/webm/1.1.0 \
    crate://crates.io/webm-sys/1.0.4 \
    crate://crates.io/webpki-root-certs/0.26.8 \
    crate://crates.io/webpki-roots/1.0.0 \
    crate://crates.io/webpki-roots/0.26.9 \
    crate://crates.io/weezl/0.1.8 \
    crate://crates.io/which/4.4.2 \
    crate://crates.io/whoami/1.6.0 \
    crate://crates.io/widestring/1.1.0 \
    crate://crates.io/win-sys/0.3.1 \
    crate://crates.io/winapi/0.2.8 \
    crate://crates.io/winapi/0.3.9 \
    crate://crates.io/winapi-build/0.1.1 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.8 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/windows/0.54.0 \
    crate://crates.io/windows/0.52.0 \
    crate://crates.io/windows/0.61.1 \
    crate://crates.io/windows/0.43.0 \
    crate://crates.io/windows/0.44.0 \
    crate://crates.io/windows/0.34.0 \
    crate://crates.io/windows/0.51.1 \
    crate://crates.io/windows/0.32.0 \
    crate://crates.io/windows/0.48.0 \
    crate://crates.io/windows-collections/0.2.0 \
    crate://crates.io/windows-core/0.51.1 \
    crate://crates.io/windows-core/0.61.0 \
    crate://crates.io/windows-core/0.54.0 \
    crate://crates.io/windows-core/0.52.0 \
    crate://crates.io/windows-future/0.2.0 \
    crate://crates.io/windows-implement/0.52.0 \
    crate://crates.io/windows-implement/0.60.0 \
    crate://crates.io/windows-interface/0.52.0 \
    crate://crates.io/windows-interface/0.59.1 \
    crate://crates.io/windows-link/0.1.1 \
    crate://crates.io/windows-numerics/0.2.0 \
    crate://crates.io/windows-registry/0.4.0 \
    crate://crates.io/windows-result/0.3.2 \
    crate://crates.io/windows-result/0.1.2 \
    crate://crates.io/windows-service/0.6.0 \
    crate://crates.io/windows-strings/0.3.1 \
    crate://crates.io/windows-strings/0.4.0 \
    crate://crates.io/windows-sys/0.45.0 \
    crate://crates.io/windows-sys/0.52.0 \
    crate://crates.io/windows-sys/0.48.0 \
    crate://crates.io/windows-targets/0.53.0 \
    crate://crates.io/windows-targets/0.42.2 \
    crate://crates.io/windows-targets/0.52.5 \
    crate://crates.io/windows-targets/0.48.5 \
    crate://crates.io/windows-version/0.1.1 \
    crate://crates.io/windows-win/3.0.0 \
    crate://crates.io/windows_aarch64_gnullvm/0.53.0 \
    crate://crates.io/windows_aarch64_gnullvm/0.42.2 \
    crate://crates.io/windows_aarch64_gnullvm/0.48.5 \
    crate://crates.io/windows_aarch64_gnullvm/0.52.5 \
    crate://crates.io/windows_aarch64_msvc/0.32.0 \
    crate://crates.io/windows_aarch64_msvc/0.42.2 \
    crate://crates.io/windows_aarch64_msvc/0.53.0 \
    crate://crates.io/windows_aarch64_msvc/0.52.5 \
    crate://crates.io/windows_aarch64_msvc/0.34.0 \
    crate://crates.io/windows_aarch64_msvc/0.48.5 \
    crate://crates.io/windows_i686_gnu/0.53.0 \
    crate://crates.io/windows_i686_gnu/0.32.0 \
    crate://crates.io/windows_i686_gnu/0.42.2 \
    crate://crates.io/windows_i686_gnu/0.52.5 \
    crate://crates.io/windows_i686_gnu/0.34.0 \
    crate://crates.io/windows_i686_gnu/0.48.5 \
    crate://crates.io/windows_i686_gnullvm/0.53.0 \
    crate://crates.io/windows_i686_gnullvm/0.52.5 \
    crate://crates.io/windows_i686_msvc/0.53.0 \
    crate://crates.io/windows_i686_msvc/0.32.0 \
    crate://crates.io/windows_i686_msvc/0.42.2 \
    crate://crates.io/windows_i686_msvc/0.52.5 \
    crate://crates.io/windows_i686_msvc/0.34.0 \
    crate://crates.io/windows_i686_msvc/0.48.5 \
    crate://crates.io/windows_x86_64_gnu/0.32.0 \
    crate://crates.io/windows_x86_64_gnu/0.42.2 \
    crate://crates.io/windows_x86_64_gnu/0.52.5 \
    crate://crates.io/windows_x86_64_gnu/0.34.0 \
    crate://crates.io/windows_x86_64_gnu/0.48.5 \
    crate://crates.io/windows_x86_64_gnu/0.53.0 \
    crate://crates.io/windows_x86_64_gnullvm/0.48.5 \
    crate://crates.io/windows_x86_64_gnullvm/0.53.0 \
    crate://crates.io/windows_x86_64_gnullvm/0.42.2 \
    crate://crates.io/windows_x86_64_gnullvm/0.52.5 \
    crate://crates.io/windows_x86_64_msvc/0.48.5 \
    crate://crates.io/windows_x86_64_msvc/0.53.0 \
    crate://crates.io/windows_x86_64_msvc/0.32.0 \
    crate://crates.io/windows_x86_64_msvc/0.42.2 \
    crate://crates.io/windows_x86_64_msvc/0.52.5 \
    crate://crates.io/windows_x86_64_msvc/0.34.0 \
    crate://crates.io/winit/0.30.9 \
    crate://crates.io/winnow/0.5.40 \
    crate://crates.io/winreg/0.10.1 \
    crate://crates.io/winreg/0.11.0 \
    crate://crates.io/winres/0.1.12 \
    crate://crates.io/wit-bindgen-rt/0.39.0 \
    crate://crates.io/wl-clipboard-rs/0.9.0 \
    crate://crates.io/wol-rs/1.0.1 \
    crate://crates.io/wyz/0.5.1 \
    crate://crates.io/x11/2.19.0 \
    crate://crates.io/x11/2.21.0 \
    crate://crates.io/x11-clipboard/0.9.2 \
    crate://crates.io/x11-dl/2.21.0 \
    crate://crates.io/x11rb/0.13.1 \
    crate://crates.io/x11rb-protocol/0.13.1 \
    crate://crates.io/xattr/1.4.0 \
    crate://crates.io/xcursor/0.3.10 \
    crate://crates.io/xdg-home/1.2.0 \
    crate://crates.io/xkbcommon-dl/0.4.2 \
    crate://crates.io/xkeysym/0.2.1 \
    crate://crates.io/zbus/3.15.2 \
    crate://crates.io/zbus_macros/3.15.2 \
    crate://crates.io/zbus_names/2.6.1 \
    crate://crates.io/zerocopy/0.8.26 \
    crate://crates.io/zerocopy/0.7.34 \
    crate://crates.io/zerocopy-derive/0.8.26 \
    crate://crates.io/zerocopy-derive/0.7.34 \
    crate://crates.io/zeroize/1.8.1 \
    crate://crates.io/zip/0.6.6 \
    crate://crates.io/zstd/0.13.1 \
    crate://crates.io/zstd/0.11.2+zstd.1.5.2 \
    crate://crates.io/zstd-safe/7.1.0 \
    crate://crates.io/zstd-safe/5.0.2+zstd.1.5.2 \
    crate://crates.io/zstd-sys/2.0.11+zstd.1.5.6 \
    crate://crates.io/zune-inflate/0.2.54 \
    crate://crates.io/zvariant/3.15.2 \
    crate://crates.io/zvariant_derive/3.15.2 \
    crate://crates.io/zvariant_utils/1.0.1 \
" 

# Add any additional dependencies if required
# libglib-2.0-0
# libgtk-3-0
RDEPENDS:${PN} = "  glib xwayland libvpx aom yuv libopus alsa-lib bindgen clang glib gtk+3 libx11 openssl pkgconfig pulseaudio zlib "
DEPENDS += " alsa-lib glib gtk+3 libx11 openssl pulseaudio zlib bindgen-native clang-native pkgconfig-native libvpx-staticdev aom-staticdev yuv-staticdev libopus-staticdev yasm zip "

# Specify the target architecture
#TARGET_ARCH = "arm64"

do_compile[env] = "VCPKG=${S}/vcpkg"

do_install() {
    install -d ${D}/${libdir}
    install -m 0755 ${WORKDIR}/arm64/libsciter-gtk.so ${D}/${libdir}
}

FILES:${PN} += " \
    ${libdir}/libsciter-gtk.so \
"

INSANE_SKIP:${PN} += "already-stripped"

# Specify the package name
PACKAGES = "${PN}"

# Ensure the package is built for i.MX8MM
COMPATIBLE_MACHINE = "arm64|(imx-nxp-bsp)"
